id=cp-04
title=Exercise 4: No Clobber
description=Use cp to copy file1 from ex04/source to ex04/dest, but do not overwrite any existing file1 in dest. Redirect any output to output.txt.
lab_dir=labs/cp/ex04
validator=cp_no_clobber
target_file=output.txt
hint=cp -n source/file1 dest/ > output.txt
completed=0
preserve_sandbox=1