id=m-n
title=Exercise 3: No Clobber Move
description=Use mv to move source/file1 to dest/file1, but do not overwrite if it exists.
lab_dir=labs/mv/ex03
validator=validate_mv_n
target_file=dest/file1
hint=mv -n source/file1 dest/
completed=1
preserve_sandbox=1
