id=m-u
title=Exercise 4: Update Move
description=Use mv to move source/file1 to dest/file1, only if source is newer.
lab_dir=labs/mv/ex04
validator=validate_mv_u
target_file=dest/file1
hint=mv -u source/file1 dest/
completed=1
preserve_sandbox=1
