id=m-v
title=Exercise 5: Verbose Move
description=Use mv to move source/file1 to dest/file1 and show detailed information about the move.
lab_dir=labs/mv/ex05
validator=validate_mv_v
target_file=dest/file1
hint=mv -v source/file1 dest/
completed=0
preserve_sandbox=1
