id=rsync-l
title=rsync -l (links)
description=Test the -l option for rsync, which copies symbolic links as symbolic links.
lab_dir=labs/rsync/ex05
validator=validate_rsync_l
target_file=dest/
hint=Use rsync -l to copy symlinks from source/ to dest/.
completed=0
preserve_sandbox=1
