id=rsync-progress
title=rsync --progress
description=Test the --progress option for rsync, which displays the progression of the file copy process.
lab_dir=labs/rsync/ex08
validator=validate_rsync_progress
target_file=dest/
hint=Use rsync --progress to see file copy progress.
completed=0
preserve_sandbox=1
